version: 0.2
phases:
  pre_build:
    run-as: root
    commands:
      - git config --global user.name "Cloudy Builder"
      - git config --global user.email "email@example.com"
  build:
    commands:
      - cd ${CODEBUILD_SRC_DIR}/..
      - curl -v https://armkeil.blob.core.windows.net/developer/Files/downloads/gnu-rm/10.3-2021.10/gcc-arm-none-eabi-10.3-2021.10-x86_64-linux.tar.bz2 | tar xjf -
      - curl https://storage.googleapis.com/git-repo-downloads/repo > repo
      - chmod +x repo
      - ./repo init -u https://github.com/rpcme/stm32f7-renode
      - ./repo sync
      - export PATH=$(pwd)/gcc-arm-none-eabi-10.3-2021.10/bin:$PATH
      - ls -l
      - ls -l stm32f7-renode
      - mkdir obj
      - mkdir bin
      - cd stm32f7-renode
      - make
artifacts:
  s3-prefix: images
  files: bin/*
