APP?=$(abspath .)
BASEPATH?=$(abspath ..)

OBJ := $(BASEPATH)/obj
LIB := $(BASEPATH)/lib
BIN := $(BASEPATH)/bin

STM := $(BASEPATH)/STM32CubeF7
FRK := $(BASEPATH)/FreeRTOS-Kernel
FRT := $(BASEPATH)/FreeRTOS-Plus-TCP
FRD := $(APP)/demo-common
SRC := $(APP)/src

FRD_MIN := $(FRD)/minimal
FRD_MAX := $(FRD)/full

C_SRCS = \
	$(STM)/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal.c \
	$(STM)/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_adc.c \
	$(STM)/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_adc_ex.c \
	$(STM)/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_cortex.c \
	$(STM)/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dac.c \
	$(STM)/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dac_ex.c \
	$(STM)/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dcmi.c \
	$(STM)/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dma.c \
	$(STM)/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dma_ex.c \
	$(STM)/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_flash.c \
	$(STM)/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_flash_ex.c \
	$(STM)/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_gpio.c \
	$(STM)/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_rcc.c \
	$(STM)/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_rng.c \
	$(STM)/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_tim.c \
	$(STM)/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_tim_ex.c \
	$(STM)/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_uart.c \
	$(STM)/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_sdmmc.c \
	$(STM)/Drivers/BSP/STM32746G-Discovery/stm32746g_discovery.c \
	$(FRK)/tasks.c \
	$(FRK)/queue.c \
	$(FRK)/event_groups.c \
	$(FRK)/list.c \
	$(FRK)/timers.c \
	$(FRK)/portable/MemMang/heap_4.c \
	$(FRK)/portable/GCC/ARM_CM7/r0p1/port.c \
	$(FRD_MIN)/TimerDemo.c \
	$(FRD_MIN)/QueueOverwrite.c \
	$(FRD_MIN)/EventGroupsDemo.c \
	$(FRD_MIN)/IntSemTest.c \
	$(FRD_MIN)/QueueSet.c \
	$(FRD_MIN)/TaskNotify.c \
	$(SRC)/stm32f7xx_hal_msp.c \
	$(SRC)/system_stm32f7xx.c \
	$(SRC)/app-hardware.c \
	$(SRC)/app-kernel-hooks.c \
	$(SRC)/app-network-hooks.c \
	$(SRC)/main.c \
	$(FRT)/FreeRTOS_IP.c \
	$(FRT)/FreeRTOS_ARP.c \
	$(FRT)/FreeRTOS_DHCP.c \
	$(FRT)/FreeRTOS_DNS.c \
	$(FRT)/FreeRTOS_Sockets.c \
	$(FRT)/FreeRTOS_TCP_IP.c \
	$(FRT)/FreeRTOS_UDP_IP.c \
	$(FRT)/FreeRTOS_TCP_WIN.c \
	$(FRT)/FreeRTOS_Stream_Buffer.c \
	$(FRT)/portable/NetworkInterface/Common/phyHandling.c \
	$(FRT)/portable/NetworkInterface/STM32Fxx/NetworkInterface.c \
	$(FRT)/portable/NetworkInterface/STM32Fxx/stm32fxx_hal_eth.c \
	$(FRT)/portable/BufferManagement/BufferAllocation_1.c

S_SRCS = $(SRC)/startup_stm32f746nghx.s
S_DEPS = $(SRC)/startup_stm32f746nghx.d

OBJS  = $(S_SRCS:.s=.o) $(C_SRCS:.c=.o)
DEPS  = $(S_SRCS:.s=.d) $(C_SRCS:.c=.d)
SUFILES = $(S_SRCS:.s=.su) $(C_SRCS:.c=.su)


# FreeRTOS-Plus-TCP port headers must come first because there are
# some naming conflicts with the ST SDK.
INC_PATH =
INC_PATH += \
	$(FRT)/portable/NetworkInterface/STM32Fxx \
	$(STM)/Drivers/STM32F7xx_HAL_Driver/Inc \
	$(STM)/Drivers/BSP/STM32746G-Discovery \
	$(STM)/Drivers/CMSIS/Include \
	$(STM)/Drivers/CMSIS/Device/ST/STM32F7xx/Include \
	$(FRK)/include \
	$(FRK)/portable/GCC/ARM_CM7/r0p1 \
	$(FRT)/portable/NetworkInterface/include \
	$(FRT)/portable/Compiler/GCC \
	$(FRT)/include \
	$(APP)/inc \
	$(APP)/demo-common/include

INC = $(INC_PATH:%=-I%)
