version: 0.2
phases:
  pre_build:
    run-as: root
    commands:
      - git config --global user.name "Cloudy Builder"
      - git config --global user.email "email@example.com"
      - apt-get -y install gpg wget
      - echo 'deb [signed-by=/usr/share/keyrings/kitware-archive-keyring.gpg] https://apt.kitware.com/ubuntu/ focal main' | tee /etc/apt/sources.list.d/kitware.list >/dev/null
      - apt-get update
      - rm /usr/share/keyrings/kitware-archive-keyring.gpg
      - apt-get -y install kitware-archive-keyring
      - apt-get update
      - apt-get -y install cmake
  build:
    commands:
      - cd ${CODEBUILD_SRC_DIR}/..
      - curl https://storage.googleapis.com/git-repo-downloads/repo > repo
      - chmod +x repo
      - ./repo init --submodules -u https://github.com/rpcme/stm32f7-renode -m configuration/stm32f7-repo.xml
      - ./repo sync --fetch-submodules
artifacts:
  s3-prefix: images
  files: bin/*
