version: 0.2
phases:
  pre_build:
    run-as: root
    commands:
      - git config --global user.name "Cloudy Builder"
      - git config --global user.email "email@example.com"
      - yum install -y jq openssl11
      - pip3 install awscli --upgrade
  build:
    commands:
      - ls -lR ${CODEBUILD_SRC_DIR_BuildArtifact}
      - cd ${CODEBUILD_SRC_DIR_BuildArtifact}/build/bin
      - echo ${certificate} | base64 -d > /etc/cert.pem
      - echo ${privatekey} | base64 -d > /etc/key.pem
      - export LD_LIBRARY_PATH=${CODEBUILD_SRC_DIR_BuildArtifact}/build/lib:${LD_LIBRARY_PATH}
      - nohup ./mqtt_demo_mutual_auth > ${CODEBUILD_SRC_DIR_BuildArtifact}/myapp-integration.log & echo $! > ${CODEBUILD_SRC_DIR_BuildArtifact}/myapp-integration.pid
      - suite_run_id=$(aws iotdeviceadvisor start-suite-run --suite-definition-id ${da_suite} --suite-run-configuration "primaryDevice={thingArn=${thing_arn},certificateArn=${certificate_arn}}" --output text --query suiteRunId)
      - ${CODEBUILD_SRC_DIR}/scripts/da-monitor.sh ${da_suite} ${suite_run_id}
      - kill $(cat ${CODEBUILD_SRC_DIR_BuildArtifact}/myapp-integration.pid)
      - cat ${CODEBUILD_SRC_DIR_BuildArtifact}/myapp-integration.log
