version: 0.2
phases:
  pre_build:
    run-as: root
    commands:
      - git config --global user.name "Cloudy Builder"
      - git config --global user.email "email@example.com"
      - yum remove -y openssl-devel
      - yum install -y jq openssl11 openssl11-devel
  build:
    commands:
      - wget https://github.com/Kitware/CMake/releases/download/v3.21.4/cmake-3.21.4-linux-x86_64.sh
      - mkdir ${CODEBUILD_SRC_DIR}/../cmake
      - sh ./cmake-3.21.4-linux-x86_64.sh --skip-license --prefix=${CODEBUILD_SRC_DIR}/../cmake
      - export PATH=${CODEBUILD_SRC_DIR}/../cmake/bin:$PATH
      - mkdir ${CODEBUILD_SRC_DIR}/credentials
      - echo ${certificate} | base64 -d > /etc/cert.pem
      - echo ${privatekey} | base64 -d > /etc/key.pem
      - cd ${CODEBUILD_SRC_DIR}
      - git submodule update --init --recursive
      - cmake -S . -Bbuild -DBUILD_TESTS=0 -DAWS_IOT_ENDPOINT="${da_endpoint}" -DCLIENT_CERT_PATH="/etc/cert.pem" -DCLIENT_PRIVATE_KEY_PATH="/etc/key.pem"
      - cd build
      - make mqtt_demo_mutual_auth
artifacts:
  s3-prefix: images
  files:
    - build/bin/*
    - build/lib/*
    - build/bin/certificates/*
